name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: .vitepress/cache
          key: vitepress-cache
      - name: Setup Node.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
      - name: Upload artifact
        if: ${{ github.event_name == 'push' || contains(github.ref, '/heads/main') }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

  deploy-pages:
    name: Deploy pages
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ github.event_name == 'push' || contains(github.ref, '/heads/main') }}
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy artifact to GitHub Pages
        uses: actions/deploy-pages@v4